version: "2"

services:
  mysql-db:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  spring-petclinic:
    image: signoz/spring-petclinic:latest
    ports:
      - "8090:8090"
    depends_on:
      mysql-db:
        condition: service_healthy
    extra_hosts:
      - "signoz:host-gateway"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=https://ingest.us.signoz.cloud:443
      - OTEL_EXPORTER_OTLP_HEADERS=signoz-access-token=05bd0e45-8ea0-4aef-9edc-3f1bc1ce4cc3
      - OTEL_RESOURCE_ATTRIBUTES=service.name=spring-petclinic
      - SPRING_PROFILES_ACTIVE=mysql
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/petclinic
      - SPRING_DATASOURCE_USERNAME=petclinic
      - SPRING_DATASOURCE_PASSWORD=petclinic
